### ISSUE TITLE
take blanking periods into account

### ISSUE THREAD

**Issue by anszom** [luamfb/tempest-lcd#2]
Most (all?) screens have nonzero blanking periods at the beginning/end of each line and at the top/bottom of the screen. You can see the full timings on X11 with xrandr --verbose. For example:

    3840x2160 (0x1d7) 594.000MHz +HSync +VSync *current +preferred
          h: width  3840 start 4016 end 4104 total 4400 skew    0 clock 135.00KHz
          v: height 2160 start 2168 end 2178 total 2250           clock  60.00Hz

You can see that although 2160 lines are displayed, each frame has 2250 lines total. So the horizontal refresh is 135KHz instead of 129.6KHz. Also, xrandr shows it plainly :)

You could also account for the missing lines when modulating the audio

**Comment by luamfb** [comment]
> Most (all?) screens have nonzero blanking periods at the beginning/end of each line and at the top/bottom of the screen.

I'm not quite sure of this. I have found some resources about this which explicitly mention CRT monitors, without mention of LCD: [1st][1] [2nd][2] [3rd][3]. Further, looking up the manpage of the `cvt` command, we have

```
       -r|--reduced
               Create a mode with reduced blanking. This allows for higher frequency signals, with a lower or equal dotclock.
               Not for Cathode Ray Tube based displays though.
``` 

I could be wrong, but because of that, I'm more inclined to think the values reported by `xrandr` are just a holdover from the days when X servers could simply assume all monitors were CRT, and these values ended up being always required by X somehow.

Besides, at least when I've tested here, using the value reported by `xrandr --verbose` always messed up with the notes' tuning.

[1]: https://shallowsky.com/linux/x-screen-blanking.html
[2]: https://en.wikipedia.org/wiki/Horizontal_blanking_interval
[3]: https://en.wikipedia.org/wiki/Vertical_blanking_interval
